import 'package:flutter/material.dart';
import '../navigator.dart';

class Residual extends StatefulWidget {
  static String routeName = '/residual';

  @override
  State<StatefulWidget> createState() {
    return InfoPageState();
  }
}

class InfoPageState extends State<Residual> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.teal,
        centerTitle: true,
        title: Text(
          'Residual waste',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.bold,
            fontSize: 26,
          ),
        ),
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back_ios),
          color: Colors.white,
          onPressed: () => Navigator.of(context).pushReplacement(
            new MaterialPageRoute(
              settings: const RouteSettings(name: '/navigator'),
              builder: (context) => MainNavigator(),
            ),
          ),
        ),
      ),
      body: Container(
        margin: EdgeInsets.all(24.0),
        child: Center(
          child: SingleChildScrollView(
            child: Column(
              children: [
                Image.network('https://waste4change.com/blog/wp-content/uploads/2019_06_15_74441_1560593399._large.jpg'
                  // width: 200,
                  // height: 200,
                ),
                Container(
                  // padding: EdgeInsets.fromLTRB(20, 20, 20, 20),
                  // margin: EdgeInsets.fromLTRB(20, 20, 20, 10),
                    child: Text('Residual waste is composed of a wide variety of materials. Pennsylvania\'s residual waste stream is predominantly ash (about 40 percent) generated by coal-burning plants and residual waste incinerators. Other residual wastes include contaminated soil, ceramics, gypsum board, linoleum, leather, rubber, textiles, glass, industrial equipment, electronics, pumps, piping, storage tanks, filters, fertilizers, pesticides, pharmaceutical waste, detergents and cleaners, photographic film and paper; wastes that contain asbestos, oil and PCBs; metal-containing wastes such as foundry sands, slags, grindings and shavings; and residues such as sludge from the treatment of public water supplies, emission control, limestabilized pickle liquor, paints, electroplating, and waste from the manufacture of lime and cement.',
                        style: TextStyle(
                        color: Colors.grey[700],
                        fontSize: 20,
                      ),
                    )
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
